[package]
name = "test_ext"
version = "0.1.0"
authors = ["Nik Bond <nikbond97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13.4"
block-utils = "0.8.2"